spring:
    profiles:
      active: default

    datasource:
      hikari:
        maximum-pool-size: 8

  # JPA
    jpa:
      hibernate:
        ddl-auto: validate
      show_sql: true
      properties:
          hibernate:
            format_sql: true

    # liquibase
    liquibase:
      change-log: classpath:config/liquibase/master.xml

    # Batch
    batch:
      job:
        enabled: false
      # JWT
    jwt:
      secret: 12345678901234567890123456789012
      access-token-valid-miliseconds: 86400000 # 24 시간
      refresh-token-valid-miliseconds: 5184000000  # 2달

    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

# logging
logging:
    level:
        org:
          hibernate:
                type:
                  descriptor:
                          sql: trace

# server
server:
  error:
    whitelabel:
          enabled: false

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# media
media:
  base:
    dir:
      name: /home/gradle/mount

cloud:
  aws:
    credentials:
      access_key: CLOUD_AWS_CREDENTIALS_ACCESS_KEY
      secret_key: CLOUD_AWS_CREDENTIALS_SECRET_KEY
    s3:
      bucket: CLOUD_AWS_S3_BUCKET
    cloudFront :
      domain : knowllydev-media.hkpark.net
    domain-uri: https://knowllydev-media.hkpark.net/
    region:
      static: ap-northeast-2
